file_format: "1"
id: Alice_XRyue60
name: Alice_XRyue60
type: shield
url: https://oshwhub.com/joba
requires: [nrfmicro_13_52840]
features:
  - keys
  - encoder
  - display
  - underglow
siblings:
  - Alice_XRyue60_left
  - Alice_XRyue60_right